name: linky-tracker
services:
  server:
    image: moifort/linky-tracker:latest
    container_name: linky-tracker-server
    restart: unless-stopped
    cpu_shares: 50
    deploy:
      resources:
        limits:
          memory: 256M
    hostname: linky-tracker
    pull_policy: always
    logging:
      driver: json-file
      options:
        max-size: 1m
    environment:
      HOST: 0.0.0.0
      PORT: "3000"
      NITRO_API_TOKEN: changeme
      NITRO_SENTRY_DSN: ""
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: /DATA/AppData/linky-tracker
        target: /app/.data
    network_mode: bridge
    labels:
      icon: https://raw.githubusercontent.com/moifort/linky-tracker/main/icon.png
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp

x-casaos:
  author: moifort
  category: Utilities
  icon: https://raw.githubusercontent.com/moifort/linky-tracker/main/icon.png
  index: /
  port_map: "3000"
  scheme: http
  store_app_id: linky-tracker
  title:
    en_us: My App
